### ISSUE TITLE
Timelimit pings

### ISSUE THREAD

**Issue by ChillerDragon** [jxsl13/TeeworldsEconDiscordModerationBot#15]
If there is active usage of the @mods ping in game there is no need to send multiple pings a minute to discord. Would be nice to have maybe a 5min cool down after pings that just sends normal messages.

**Comment by ChillerDragon** [comment]
sorri Alessandro lmao

**Comment by jxsl13** [comment]
good idea

**Comment by jxsl13** [comment]
done.

**Comment by ChillerDragon** [comment]
Closed by https://github.com/jxsl13/TeeworldsEconDiscordModerationBot/commit/189bbac85783536fc89a5cbb823e85e17585184a and https://github.com/jxsl13/TeeworldsEconDiscordModerationBot/commit/5e555209aa62ca4a4bd7871d294c3e587fd23a72
